# Netlify configuration file

# Build settings
[build]
  # Directory to publish (output of the build)
  publish = "dist"
  # Build command
  command = "npm run build"

# Redirects and rewrites
[[redirects]]
  # Redirect all routes to index.html for SPA routing
  from = "/*"
  to = "/index.html"
  status = 200

# Headers
[[headers]]
  # Define headers for all files
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.supabase.co; img-src 'self' data: https://*.pexels.com https://*.unsplash.com https://*.cloudinary.com; script-src 'self' 'unsafe-inline' https://js.stripe.com; style-src 'self' 'unsafe-inline'; frame-src https://js.stripe.com;"

# Environment variables
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"